version: "2.1"

services:
    nextepc:
        build:
            context: .
        image:  ydagne/nextepc:1.0
        cap_add:
            -  NET_ADMIN
        sysctls:        
            net.ipv6.conf.all.disable_ipv6: 0
        devices:
            -  "/dev/net/tun"
        container_name: epc
        ports:
            -  "8000:3000"
        networks:
            epc_net:
                ipv4_address: 172.16.238.10
                ipv6_address: 2001:3984:3989::10

        # --------OPTIONAL but RECOMMENDED------------------------------------------
        # Mount volumes for MongoDB data (HSS database)
        # Remember to set the source path to appropriate location in the host system
        # If no volumes are mounted MongoDB database (at /var/lib/mongo/), then all
        # subscriber information will be lost when the container is stopped.
        volumes:
            - ./mongo/db:/var/lib/mongo
            - ./mongo/log:/var/log/mongo
            # Mount configuration files to override default values
            - ./conf/mme.conf:/nextepc/install/etc/nextepc/mme.conf

networks:
    epc_net:
        enable_ipv6: true
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                  gateway: 172.16.238.1
                - subnet: 2001:3984:3989::/64
                  gateway: 2001:3984:3989::1
